{"name": "Sign up a new user successfully", "status": "failed", "statusDetails": {"message": "AssertionError: assert ('message' in '' or 'error' in '')", "trace": "fixturefunc = <function check_signup_success at 0x0000029F90223560>, request = <FixtureRequest for <Function test_sign_up_a_new_user_successfully>>, kwargs = {}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if inspect.isgeneratorfunction(fixturefunc):\n            fixturefunc = cast(Callable[..., Generator[FixtureValue]], fixturefunc)\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n                             ^^^^^^^^^^^^^^^^^^^^^\n\n.venv\\Lib\\site-packages\\_pytest\\fixtures.py:929: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @allure.step(\"Debería recibir un mensaje de éxito o que el usuario ya existe\")\n    @then(\"I should receive a success message or user already exists\")\n    def check_signup_success():\n        res = response_data[\"response\"]\n        assert res.status_code == 200\n        data = res.json()\n>       assert \"message\" in data or \"error\" in data\nE       AssertionError: assert ('message' in '' or 'error' in '')\n\nfeatures\\steps\\test_api.py:89: AssertionError"}, "description": "As a user\nI want to sign up and log in to the system\nSo that I can access protected features", "steps": [{"name": "Given I have a unique valid username and password", "status": "passed", "start": 1748962364600, "stop": 1748962364600}, {"name": "When I send a signup request", "status": "passed", "start": 1748962364600, "stop": 1748962365086}, {"name": "Then I should receive a success message or user already exists", "status": "failed", "statusDetails": {"message": "AssertionError: assert ('message' in '' or 'error' in '')\n", "trace": "  File \"C:\\Users\\daviv\\OneDrive\\Documentos\\demoblazeTesting\\.venv\\Lib\\site-packages\\pytest_bdd\\scenario.py\", line 240, in _execute_step_function\n    return_value = call_fixture_func(fixturefunc=context.step_func, request=request, kwargs=kwargs)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\daviv\\OneDrive\\Documentos\\demoblazeTesting\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\daviv\\OneDrive\\Documentos\\demoblazeTesting\\features\\steps\\test_api.py\", line 89, in check_signup_success\n    assert \"message\" in data or \"error\" in data\n"}, "start": 1748962365086, "stop": 1748962365089}], "start": 1748962364600, "stop": 1748962365089, "uuid": "cdd07812-e9e9-e058-09f1-a8f49a6a3571", "historyId": "3cefca0d3ba7341b0f04fa5c9d539290.d41d8cd98f00b204e9800998ecf8427e", "testCaseId": "3cefca0d3ba7341b0f04fa5c9d539290", "fullName": "features\\login_api.feature:Sign up a new user successfully", "labels": [{"name": "host", "value": "vidd4"}, {"name": "thread", "value": "19752-MainThread"}, {"name": "framework", "value": "pytest-bdd"}, {"name": "language", "value": "cpython3"}, {"name": "feature", "value": "User Authentication"}]}